- Capability:
  - Name: SnowCreateTicket
    Description: Open a new incident ticket in ServiceNow
    Parameter:
    - Name: Environment
      Description: ServiceNow instance to use
      Default: DEV
    - Name: System
      Description: INKA, SWCI, Support Unit or Support Unit ID for this MARSNode
      Default: ${INKA}
    - Name: ReportedOn
      Description: INKA, SWCI, Support Unit or Support Unit ID for this MARSNode
      Default: ${INKA}
    - Name: Details
      Description: Incident details
      Default: __EVENT_DETAILS__
    - Name: Summary
      Description: Short description
      Default: __EVENT_SUMMARY__
    - Name: NetcoolID
      Description: ID of the initial Event in Netcool
      Mandatory: false
    - Name: WorkNotes
      Description: Work notes to attach to the ticket
      Default: __ISSUE_LOG__
    - Name: Urgency
      Description: Urgency of the incident
      Default: 1
    - Name: Impact
      Description: Impact of the incident
      Default: 4
    - Name: Level
      Description: Assignment level of the incident
      Default: 2
  Applicability:
  - Priotity: 100
    ModelFilter:
    - TrueFilter:
        {}
